name: weather

on:
  schedule:
  - cron: "0 14 * * *"
  workflow_dispatch:
  
env:
  MAIL_USER_EMAIL: ${{ secrets.MAIL_USER_EMAIL }}
  MAIL_USER_PASS: ${{ secrets.MAIL_USER_PASS }}
  MAIL_FROM: ${{ secrets.MAIL_FROM }}
  MAIL_TO: ${{ secrets.MAIL_TO }}
  ACCU_WEATHER_API_KEY: ${{ secrets.ACCU_WEATHER_API_KEY }}
  TENOR_API_KEY: ${{ secrets.TENOR_API_KEY }}

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn install
    - run: npm run dev
